title: 褴褛飞旋的博客
url: https://nsctechart.github.io/

# Owner/author information
owner:
  name: Shaocong Nie
  avatar: avatar.jpg
  #cv: https://nsctechart.github.io/file/cv/MyCV.pdf
  twitter: Noob_Coder22
  github: nscTechArt
  bilibili: 21109252
  zhihu: https://www.zhihu.com/people/leave-53-6


# Links to include in top navigation
links:
  - title: About Me
    url: /
  - title: Unity
    url: /Unity/
  - title: Unreal
    url: /Unreal/
  - title: Blender
    url: /Blender/
  - title: CG
    url: /CG/
  - title: Blogs
    url: /blogs/

# 以下暂时不用修改------------------------------------------------------------------------------------

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
